---
version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # volumes:
    #   - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  logstash:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/logstash/logstash:6.5.4
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logs:/logs

  # https://www.elastic.co/guide/en/kibana/current/docker.html
  # DEFAULT:
  #   server.name kibana
  #   server.host "0"
  #   elasticsearch.url http://elasticsearch:9200
  #   xpack.monitoring.ui.container.elasticsearch.enabled true
  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:6.5.4
    ports:
      - 5601:5601
